= TeamCity DSL Extensions
:uri-teamcity: https://www.jetbrains.com/teamcity/[TeamCity]

A library that extends the {uri-teamcity} DSL to create build configurations based on a Gradle build template.

== Using the library

To use the library add the following repository and dependency to the Maven POM in the `.teamcity` directory.

[source, xml]
----
    <repository>
        <id>bintray-rodm-maven</id>
        <name>bintray</name>
        <url>https://dl.bintray.com/rodm/maven</url>
    </repository>

    ...

    <dependency>
        <groupId>com.github.rodm</groupId>
        <artifactId>teamcity-dsl-extensions</artifactId>
        <version>0.2</version>
        <scope>compile</scope>
    </dependency>
----

Import the `pipeline` function

    import com.github.rodm.teamcity.pipeline

Use the DSL method to create a pipeline with one or more stages, and each stage with one or more build configurations.

The example below shows the creation of a build template and a pipeline with 2 stages. The first stage defines
default settings for each of the following build configurations. Each stage is represented in TeamCity as a composite
build configuration with dependencies on each build configuration defined in the stage. Build configurations in
subsequent stages have a dependency on the previous stage build configuration.

[source, kotlin]
----
    import com.github.rodm.teamcity.pipeline

    project {

        val buildTemplate = gradleBuildTemplate {
            id("GradleBuild")
            name = "Gradle Build"
            ...
        }

        pipeline {
            stage("Stage 1") {
                defaults {
                    failureConditions {
                        executionTimeoutMin = 10
                    }
                }

                build {
                    templates(buildTemplate)
                    id("Build1")
                    name = "Build 1"
                }

                build {
                    templates(buildTemplate)
                    id("Build2")
                    name = "Build 2"
                }
            }
            stage("Stage 2") {
                build {
                    templates(buildTemplate)
                    id("ExamplePublish")
                    name = "Publish"
                }
            }
        }
    }
----

Configuring a GitHub issue tracker can be defined using the `githubIssueTracker` function

[source, kotlin]
----
    import com.github.rodm.teamcity.project.githubIssueTracker

    project {
        features {
            githubIssueTracker {
                displayName = "TeamCityDSLExtensions"
                repository = "https://github.com/rodm/teamcity-dsl-extensions"
                pattern = """#(\d+)"""
            }
        }
    }
----

== Compatibility

The library is compatible with TeamCity 2018.1.

== License

This plugin is available under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].
