= TeamCity DSL Extensions
:uri-teamcity: https://www.jetbrains.com/teamcity/[TeamCity]
:uri-teamcity-documentation: https://confluence.jetbrains.com/display/TCD18
:uri-teamcity-artifact-path: {uri-teamcity-documentation}/Configuring+General+Settings#ConfiguringGeneralSettings-ArtifactPaths
:uri-teamcity-artifact-dep: {uri-teamcity-documentation}/Dependent+Build#DependentBuild-ArtifactDependency
:library-version: 0.2

A library that extends the {uri-teamcity} DSL to create build configurations based on a Gradle build template.

== Using the library

To use the library add the following repository and dependency to the Maven POM in the `.teamcity` directory.

[source, xml]
----
    <repository>
        <id>bintray-rodm-maven</id>
        <name>bintray</name>
        <url>https://dl.bintray.com/rodm/maven</url>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>

    ...

    <dependency>
        <groupId>com.github.rodm</groupId>
        <artifactId>teamcity-dsl-extensions</artifactId>
        <version>{library-version}</version>
        <scope>compile</scope>
    </dependency>
----

Import the `pipeline` function

    import com.github.rodm.teamcity.pipeline

Use the DSL method to create a pipeline with one or more stages, and each stage with one or more build configurations.

The example below shows the creation of a build template and a pipeline with 2 stages. The first stage defines
default settings for each of the following build configurations. Each stage is represented in TeamCity as a composite
build configuration with dependencies on each build configuration defined in the stage. Build configurations in
subsequent stages have a dependency on the previous stage build configuration.

[source, kotlin]
----
    import com.github.rodm.teamcity.pipeline

    project {

        val buildTemplate = gradleBuildTemplate {
            id("GradleBuild")
            name = "Gradle Build"
            ...
        }

        pipeline {
            stage("Stage 1") {
                defaults {
                    failureConditions {
                        executionTimeoutMin = 10
                    }
                }

                build {
                    templates(buildTemplate)
                    id("Build1")
                    name = "Build 1"
                }

                build {
                    templates(buildTemplate)
                    id("Build2")
                    name = "Build 2"
                }
            }
            stage("Stage 2") {
                build {
                    templates(buildTemplate)
                    id("ExamplePublish")
                    name = "Publish"
                }
            }
        }
    }
----

The default dependency for a stage can be overridden by using the `dependsOn` function. A stage can depend on one or
more earlier stages.

[source, kotlin]
----
    import com.github.rodm.teamcity.pipeline

    project {
        pipeline {
            val stage1 = stage("Stage 1") {
                ...
            }
            stage("Stage 2") {
                ...
            }
            stage("Stage 3") {
                dependsOn (stage1)
                ...
            }
        }
    }
----

Artifacts can be defined using the `Artifact` type. The `producerRules` and `consumerRules` patterns define the
paths of build output artifacts collected from a producing build and the paths the artifacts are written to for
a consuming build. More on the patterns can be found in TeamCity documentation,
{uri-teamcity-artifact-path}[Artifact Paths] and {uri-teamcity-artifact-dep}[Artifact Dependency].

    val artifact = Artifact("producerRules", "consumerRules")


The `Artifact` is passed to the build that produces the artifact using the `produces` extension function and
passed to the build that uses the artifact using the `consumes` extension function.

[source, kotlin]
----
    pipeline {
        val artifact = Artifact("producerRules", "consumerRules")
        stage("Stage1") {
            build {
                name = "Build1"
                produces(artifact)
            }
            build {
                name = "Build2"
                consumes(artifact)
            }
        }
    }
----

Configuring a GitHub issue tracker can be defined using the `githubIssueTracker` function

[source, kotlin]
----
    import com.github.rodm.teamcity.project.githubIssueTracker

    project {
        features {
            githubIssueTracker {
                displayName = "TeamCityDSLExtensions"
                repository = "https://github.com/rodm/teamcity-dsl-extensions"
                pattern = """#(\d+)"""
            }
        }
    }
----

== Compatibility

The library is compatible with TeamCity 2018.2.

== License

The library is available under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].
